import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { readEventData, repositoryRoot, validateRepositoryEvents } from "./data-utils";

const events = await readEventData();
const validation = validateRepositoryEvents(events);

if (!validation.ok) {
  console.error("Cannot generate event index because data validation failed:");
  for (const error of validation.errors) {
    console.error(`- ${error}`);
  }
  process.exit(1);
}

const outputDirectory = path.join(repositoryRoot, "src", "generated");
const outputPath = path.join(outputDirectory, "eventIndex.ts");
const source = `// This file is generated by scripts/generate-index.ts. Do not edit manually.
import type { EventRecord } from "../lib/eventTypes";

export const events: EventRecord[] = ${JSON.stringify(events, null, 2)};
`;

await mkdir(outputDirectory, { recursive: true });
await writeFile(outputPath, source, "utf8");

console.log(`Generated ${path.relative(repositoryRoot, outputPath)} with ${events.length} events.`);
